### ISSUE TITLE
426 Upgrade Required

### ISSUE THREAD

**Issue by lolomin** [Eugeny/tabby-connection-gateway#2]
Hi,

Ran docker 👍 
docker run -e TABBY_AUTH_TOKEN=XXXXXXXXXXXXXX -p 9000:9000 ghcr.io/eugeny/tabby-connection-gateway:master --token-auth --host 0.0.0.0

But when tried to connect from Tabby Windows App v1.0.173 with Config Sync Host configured I got :

INFO:server:Token auth enabled
INFO:GatewayServer:Listening on 0.0.0.0:9000
INFO:websockets.server:server listening on 0.0.0.0:9000
INFO:websockets.server:connection failed (426 Upgrade Required)
INFO:websockets.server:connection closed
INFO:websockets.server:connection failed (426 Upgrade Required)
INFO:websockets.server:connection closed
INFO:websockets.server:connection failed (426 Upgrade Required)
INFO:websockets.server:connection closed
INFO:websockets.server:connection failed (426 Upgrade Required)
INFO:websockets.server:connection closed
INFO:websockets.server:connection failed (426 Upgrade Required)
INFO:websockets.server:connection closed
INFO:websockets.server:connection failed (426 Upgrade Required)

Could you please tell if I miss something ?

Regards,

Laurent

**Comment by Eugeny** [comment]
Hi, this service is designed to be used with Tabby Web (self-hosted https://github.com/Eugeny/tabby-web or cloud http://tabby.sh/app). It's just a thin proxy that allows starting TCP connections from within a browser - you can't use it as a bastion/jumphost.

**Comment by lolomin** [comment]
Thks for your answer, sorry not understood that tabby-web was need in order to sync config/vault from Tabby Terminal/App to tabby-gateway, now trying to installing tabby-web :)

**Comment by Eugeny** [comment]
Just to clarify - you don't need the gateway if you only want to sync your config - you only need it if you want to do actual SSH connections _from_ tabby-web.
